### ISSUE TITLE
Read this kthx.

### ISSUE THREAD

**Issue by impacts2** [DrOreo002/DrOreo002#1]
Hey, what's your discord id I'd like to get a paid program or lesson thing I can pay via Paypal, Bitcoin or even dls.

**Comment by DrOreo002** [comment]
> Hey, what's your discord id I'd like to get a paid program or lesson thing I can pay via Paypal, Bitcoin or even dls.

Sorry I don't have time to teach you, even tho its paid. I have job to get done
